alias s="cd ~/site/"
alias sp="cd ~/site/python/"
alias sj="cd ~/site/javascript"
alias sg="cd ~/site/git/"
alias sc="cd ~/site/git/code_share/"
alias sd="cd ~/site/git/dotfiles/"
alias d="cd ~/Downloads/"
