alias e="cd ~/site/esri"
alias ej="cd ~/site/esri/arcgis-js-api-4"
alias ew="cd ~/site/esri/arcgis-web-components"
alias eww="cd ~/site/esri/arcgis-web-components-alt"
alias ec="cd ~/site/esri/calcite-design-system/packages/calcite-components/src/components"
alias sm="cd ~/site/esri/arcgis-web-components/packages/map-components/src/migration"