# A config file for pre-commit.com
#
# Documentation
# https://github.com/specifysystems/code-principles/blob/main/pre-commit-hooks.md

default_language_version:
  python: python3
default_stages:
  - commit
  - merge-commit
exclude: ^(lib|.idea)
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-docstring-first
      - id: check-xml
      - id: check-shebang-scripts-are-executable
      - id: check-merge-conflict
      - id: check-symlinks
      - id: detect-private-key
      - id: mixed-line-ending
      - id: requirements-txt-fixer
      - id: fix-byte-order-marker
      - id: fix-encoding-pragma
      - id: forbid-new-submodules

  - repo: https://github.com/maxxxxxdlp/pre-commit
    rev: v1.0.6
    hooks:
      - id: tsc
      - id: regex-blacklist
        args:
          - ~/site/git/dotfiles/git/regex-blacklist.txt

  - repo: https://github.com/codespell-project/codespell
    rev: v2.1.0
    hooks:
      - id: codespell
        args:
          - --skip="./node_modules/,package-lock.json,./.idea/"

  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black
        args:
          - --line-length=72

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-bugbear
        args:
          # these settings are needed to make flake8 compatible with black
          - --max-line-length=88
          - --select=C,E,F,W,B,B950
          - --extend-ignore=E203,E501

  - repo: https://github.com/terrencepreilly/darglint
    rev: v1.8.1
    hooks:
      - id: darglint
        args:
          - -v 2

  - repo: https://github.com/PyCQA/pydocstyle
    rev: 6.1.1
    hooks:
      - id: pydocstyle

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.942
    hooks:
      - id: mypy
        exclude: ^docs/

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.32.0
    hooks:
      - id: pyupgrade

  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v1.20.1
    hooks:
      - id: setup-cfg-fmt

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v2.6.2
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.5.1
          - '@prettier/plugin-xml@^0.13.1'
          - prettier-plugin-package@1.3.0
          - prettier-plugin-sh@0.8.1
          - prettier-plugin-tailwind-css@1.5.0
          - prettier-plugin-firebase-database@1.0.1

  - repo: https://github.com/awebdeveloper/pre-commit-stylelint
    rev: 0.0.2
    hooks:
      - id: stylelint
        files: \.(css|scss|sass|js|jsx|ts|tsx)$
        additional_dependencies:
          - stylelint@14.2.0
          - stylelint-config-prettier@9.0.3
          - stylelint-config-standard@24.0.0

  - repo: https://github.com/pre-commit/mirrors-eslint
    rev: v8.13.0
    hooks:
      - id: eslint
        types: [text]
        types_or: [javascript, jsx, ts, tsx]
        additional_dependencies:
          - '@maxxxxxdlp/eslint-config@^1.0.9'

  - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
    rev: v1.2.4
    hooks:
      - id: python-safety-dependencies-check

  - repo: https://github.com/jorisroovers/gitlint
    rev: v0.17.0
    hooks:
      - id: gitlint

  - repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.1.0
    hooks:
      - id: docker-compose-check

  - repo: https://github.com/markdownlint/markdownlint
    rev: v0.11.0
    hooks:
      - id: markdownlint
        files: \.md$
        args:
          - --git-recurse

  - repo: https://github.com/maxxxxxdlp/mirrors-jscpd
    rev: v3.3.26
    hooks:
      - id: jscpd
        types: [text]
