# pre-commit install
# pre-commit autoupdate
# pre-commit run --all-files
# SKIP=flake8 git commit -m "foo"
default_language_version:
  python: python3
default_stages:
  - commit
  - merge-commit
exclude: ^(lib|.idea)
repos:
 - repo: https://github.com/pre-commit/pre-commit-hooks
   rev: v3.4.0
   hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
    - id: check-case-conflict
    - id: check-docstring-first
    - id: check-json
    - id: check-merge-conflict
    - id: check-symlinks
    - id: detect-private-key
    - id: mixed-line-ending
    - id: requirements-txt-fixer

 - repo: https://github.com/maxxxxxdlp/pre-commit
   rev: v1.0.1
   hooks:
    - id: tsc
    - id: regex-blacklist
      args: [ /Users/mambo/site/git/dotfiles/git/regex-blacklist.txt ]

 - repo: https://github.com/psf/black
   rev: 20.8b1
   hooks:
    - id: black

 - repo: https://gitlab.com/pycqa/flake8
   rev: 3.9.0
   hooks:
    - id: flake8
      additional_dependencies: [flake8-bugbear]

 - repo: https://github.com/PyCQA/pydocstyle
   rev: 6.0.0
   hooks:
    - id: pydocstyle

 - repo: https://github.com/pre-commit/mirrors-mypy
   rev: v0.812
   hooks:
    - id: mypy
      exclude: ^docs/

 - repo: https://github.com/asottile/pyupgrade
   rev: v2.12.0
   hooks:
    - id: pyupgrade

 - repo: https://github.com/asottile/setup-cfg-fmt
   rev: v1.17.0
   hooks:
    - id: setup-cfg-fmt

 - repo: https://github.com/Lucas-C/pre-commit-hooks-nodejs
   rev: v1.1.1
   hooks:
    - id: dockerfile_lint

 - repo: https://github.com/Lucas-C/pre-commit-hooks-safety
   rev: v1.2.1
   hooks:
    - id: python-safety-dependencies-check

 - repo: https://github.com/lovesegfault/beautysh
   rev: 6.0.1
   hooks:
    - id: beautysh
      args: [--indent-size=2]

 - repo: https://github.com/jorisroovers/gitlint
   rev: v0.15.0
   hooks:
    - id: gitlint

 - repo: https://github.com/IamTheFij/docker-pre-commit
   rev: v2.0.0
   hooks:
    - id: docker-compose-check

 - repo: https://github.com/markdownlint/markdownlint
   rev: v0.11.0
   hooks:
    - id: markdownlint
      args: [--git-recurse]

 - repo: https://github.com/sirosen/check-jsonschema
   rev: 0.3.0
   hooks:
    - id: check-github-workflows
    - id: check-github-actions
