#!/bin/bash

# Exit immediately if any command fails
#set -e

# Redirect output to stderr.
#exec 1>&2

# Define colors
RED='\033[0;31m'
NC='\033[0m'

HOOKS_PATH=`git config core.hookspath`
ROOT_DIR=`git rev-parse --show-toplevel`

# Run checks
. "${HOOKS_PATH}pre-commit_default"
. "${HOOKS_PATH}pre-commit_tsc"
. "${HOOKS_PATH}pre-commit_check-blacklist"

