#!/bin/bash

# Run npx tsc to check for typescript error

# find tsconfig.json, if there is any
tsconfig="$(find ${ROOT_DIR} -type d \( -name node_modules -o -name .idea \) -prune -false -o -name 'tsconfig.json')"
if [ -n "$tsconfig" ];
then
  result=`cd "${tsconfig%/*}/" && npx tsc --noEmit --pretty true`
  if [ -n "$result" ]
  then
    echo "$result"
    echo -e "${RED}TypeScript typechecker returned errors${NC}"
    exit 1
  fi
fi

